get_proto:
	rm -rf protos
	rm -rf helloworld_proto
	git clone --depth 1 --branch v.1.1 https://github.com/difaagh/helloworld_proto.git
	mv helloworld_proto/stub/nodejs protos
	rm -rf helloworld_proto
