get_proto:
	rm -rf protos
	rm -rf helloworld_proto
	git clone --depth 1 --branch v.1.3 https://github.com/difaagh/helloworld_proto.git
	mkdir protos
	mv ./helloworld_proto/helloworld.proto ./protos
	rm -rf helloworld_proto
